function expandAdvancePayments() {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("AdvancePayments");
  const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 18).getValues(); // A:R

  let results = [];

  data.forEach((row, index) => {
    const houseNo = row[0];                    // A
    const payType = (row[11] || "").toString().trim(); // L
    if (!houseNo) return;

    // ✅ include ล่วงหน้า + ชำระหนี้ค้าง
    if (payType !== "ล่วงหน้า" && payType !== "ชำระหนี้ค้าง") return;

    const months = parseInt(row[16], 10);      // Q No Months
    const totalPayment = parseFloat(row[8]);   // I ยอดชำระ
    const startDate = new Date(row[14]);       // O StartMonth (date)

    if (isNaN(months) || months <= 0 || isNaN(totalPayment) || isNaN(startDate)) {
      Logger.log(`⚠️ Skip row ${index + 2} invalid data`);
      return;
    }

    const monthlyPayment = totalPayment / months;

    for (let i = 0; i < months; i++) {
      const targetDate = new Date(startDate);
      targetDate.setMonth(targetDate.getMonth() + i);
      targetDate.setDate(1);

      const payMonthText = Utilities.formatDate(
        targetDate,
        "Asia/Bangkok",
        "MMMM yy" // เช่น "มกราคม 26"
      );

      results.push([
        row[0], row[1], row[2], row[3], row[4], row[5],
        row[6], row[7],
        parseFloat(monthlyPayment.toFixed(2)),
        row[9], row[10], row[11],
        row[12], row[13],
        targetDate,    // ✅ Column O = Date (ชำระเดือน)
        payMonthText   // ✅ Column P = Text สำหรับแสดงผล
      ]);
    }
  });

  Logger.log("Generated rows: " + results.length);
  return results;
}


function createTimeDrivenTriggers() {
  // Trigger daily after data is expected to be updated
  ScriptApp.newTrigger('updateAdvancePayments')
    .timeBased()
    .everyDays(1)
    .atHour(10) // Assuming data is refreshed before 10 AM
    .create();
}

function updateAdvancePayments() {
  const results = expandAdvancePayments();
  
  if (!results || results.length === 0) {
    Logger.log("⚠️ No data generated by expandAdvancePayments(). Skipping write.");
    return;
  }

  const sheetName = "AdvancePaymentsBreakdown";  // Make sure name matches EXACTLY
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let sheet = ss.getSheetByName(sheetName);

  if (!sheet) {
    Logger.log("❗ Sheet not found, creating new one: " + sheetName);
    sheet = ss.insertSheet(sheetName);
  } else {
    Logger.log("✅ Sheet found: " + sheetName + ", clearing contents.");
    sheet.clearContents();
  }

  const headers = [
    "บ้านเลขที่", "Soi", "ชื่อสมาชิก", "เบอร์โทร", "เล่มที่", "เลขที่ใบเสร็จ",
    "วันที่ใบเสร็จ", "วันที่ชำระ", "ยอดชำระ", "ประเภทการชำระ", "วิธีชำระ",
    "ชำระล่วงหน้า", "ส่วนกลางเดือน", "ถึงเดือน", "ชำระเดือน", "date"
  ];

  Logger.log("📝 Writing headers and " + results.length + " data rows...");

  sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
  sheet.getRange(2, 1, results.length, results[0].length).setValues(results);
  


  // Restore formulas for columns P and Q
   const lastRow = sheet.getLastRow();
  if (lastRow >= 2) {
    // ✅ Keep only Name lookup in column Q
    sheet.getRange("Q2").setFormula(
      `=IF(OR(ISBLANK(A2), ISERROR(A2)), "", XLOOKUP(A2, INDEX(SNPNameList,,1), INDEX(SNPNameList,,8)))`
    );

    if (lastRow > 2) {
      sheet.getRange("Q2").copyTo(sheet.getRange(`Q3:Q${lastRow}`));
    }
  }




  Logger.log("✅ Data written to " + sheetName + " successfully.");
  sheet.getRange("R1").setValue("✅ Updated: " + new Date().toLocaleString("th-TH"));
}


function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu("💬 SNP Tools")
    .addItem("↻ Update Advance Payments", "updateAdvancePayments")
    .addSeparator()
    .addItem("📤 Send Template 1 (Manual)", "runTemplate1Manually")
    .addItem("📤 Send Template 2 (Manual)", "runTemplate2Manually")
    .addItem("📅 Auto Send Today", "DailyReportToLineFlexAuto")
    .addItem(" Test Flex New Template", "sendTestFlex")
    .addToUi();
}

function runTemplate1Manually() {
  DailyReportToLineFlexAuto("template1");
}

function runTemplate2Manually() {
  DailyReportToLineFlexAuto("template2");
}


// แก้ไขข้อมูลที่นี้ก่อนใช้งาน //

// === GLOBALS - NO openById used === //

// === SETTINGS ===

const MODE = "auto"; // "auto" (default) or "template1" or "template2"

//"auto" — will pick Template 1 for day ≥ 25, and Template 2 for day 1–10.
//"template1" — force test of Template 1.
//"template2" — force test of Template 2. ( Including House No. pending payment)

const ss = SpreadsheetApp.getActiveSpreadsheet();
const ssName = "รายงานส่วนกลาง-line"; // common fee report for noti
const ccName = "ConsolidatePayments"; // for chatabot 
const flexMessageSheet = ss.getSheetByName("FlexMessage"); // Flex layout content


const accessToken = 'KH1mcbFgYsIbHxBxNNfqzqKGg/NOjHQ6ZfjDpZTgNI9q5A1Jf7RAWGcYcBWs3YSk83Jp97ULkZDrGJMLQTOVkWu41UeJwDibVtJdvHF+DarkEVHepJXEktH36IK+b6l4MSSW+xTRTMgEK3Lt+A9gPgdB04t89/1O/w1cDnyilFU='; // shortened for brevity
const groupId = 'Cb29d3b8bd9de34eacb3128c0c3b06453';  // กลุ่มกรรมการ SNP1 2568 (ใหม่) Cb29d3b8bd9de34eacb3128c0c3b06453 SNP1 กรรมการ 2566 : C283b453cfd30b19c772f9112e6a96b8f   , Test group : C91aa0ac74c0181b7f9b6bc83ec3ccd8b
const userId = 'U458ef97b64613330dcf9d77cd5258193';

// Predefined Flex Message Data Structure (can expand later)

const CommonfeeReport = {
  sdate: "",
  sdatetime: "",
  CurrentMonth: "",
  NumPaid: "",
  NumAdvancePaid: "",
  NumPending: "",
  CurrentMonthAmount: "",
  HouseNoPending: ""
};

const line_endpoint = `https://api.line.me/v2/bot/message/reply`;    // use for chatbot

const data_sheet = ss.getSheetByName(ccName);   // Database for chat bot {consolidatePayment sheet}


const data_table = data_sheet.getRange(2, 1, data_sheet.getLastRow() - 1, data_sheet.getLastColumn()).getValues();
// get dataranges from sheet ConsolidatePayments

const noresult = `ไม่พบข้อมูลที่ค้นหา` 








function DailyReport2ToLine() {
  const reportSheet = ss.getSheetByName(ssName);
  if (!reportSheet) {
    Logger.log("❌ Sheet not found: " + ssName);
    return;
  }

  let msg = "รายงานรับชำระค่าส่วนกลางวันที่ " + DateConvert(reportSheet.getRange('B2').getValue()) + "\n" +
            reportSheet.getRange('A3').getValue() + " " + reportSheet.getRange('B3').getValue() + "\n" +
            reportSheet.getRange('A4').getValue() + " " + formatNumber(reportSheet.getRange('B4').getValue()) + "\n" +
            reportSheet.getRange('A5').getValue() + " " + formatNumber(reportSheet.getRange('B5').getValue()) + "\n" +
            reportSheet.getRange('A6').getValue() + " " + formatNumber(reportSheet.getRange('B6').getValue()) + "\n" +
            reportSheet.getRange('A7').getValue() + " " + formatNumber(reportSheet.getRange('B7').getValue()) + "\n" +
            reportSheet.getRange('A8').getValue() + " " + reportSheet.getRange('B8').getValue() + "\n" +
            reportSheet.getRange('A9').getValue() + " " + formatDateTime(new Date()) + "\n";   // live send time (was stale cell B9)

  Logger.log(msg);
  sendLineMessage(accessToken, groupId, msg);
}

function sendLineMessage(token, recipientId, text) {
  const payload = JSON.stringify({
    to: recipientId,
    messages: [{ type: 'text', text: text }]
  });

  const options = {
    method: 'post',
    contentType: 'application/json',
    headers: {
      'Authorization': 'Bearer ' + token
    },
    payload: payload
  };

  UrlFetchApp.fetch('https://api.line.me/v2/bot/message/push', options);
}


function formatNumber(number) {
  return Number(number || 0).toLocaleString("th-TH", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}


function formatDateTime(datetime) {
  if (Object.prototype.toString.call(datetime) !== "[object Date]" || isNaN(datetime)) {
    return "-";
  }

  const day = datetime.getDate().toString().padStart(2, '0');
  const month = (datetime.getMonth() + 1).toString().padStart(2, '0');
  const year = datetime.getFullYear();
  const hours = datetime.getHours().toString().padStart(2, '0');
  const minutes = datetime.getMinutes().toString().padStart(2, '0');

  return `${day}/${month}/${year} เวลา ${hours}:${minutes}`;
}


function DailyReportToLineFlexAuto(MODE = "auto") {
  const today = new Date();
  const day = today.getDate();

  let templateType;

  if (MODE === "template1") {
    templateType = "template1"; // manual override
  } else if (MODE === "template2") {
    templateType = "template2"; // manual override
  } else {
    // Auto logic based on day
    if (day >= 1 && day <= 10) {
      templateType = "template2";
    } else if (day >= 25 && day <= 31) {
      templateType = "template1";
    } else {
      Logger.log("📭 No message sent on day " + day);
      return;
    }
  }

  if (templateType === "template1") {
    DailyReportToLineFlexTemplate1();
  } else {
    DailyReportToLineFlexTemplate2();
  }
}



function DailyReportToLineFlexTemplate1() {
  sendFlexReportUsingTemplate("B2");
}

function DailyReportToLineFlexTemplate2() {
  sendFlexReportUsingTemplate("C2");
}

function sendFlexReportUsingTemplate(cellRef, targetId = groupId) {
  const reportSheet = ss.getSheetByName(ssName);
  if (!reportSheet || !flexMessageSheet) return;

  const CommonfeeReport = {
    sdate: DateConvert(reportSheet.getRange('B2').getValue()),
    sdatetime: formatDateTime(new Date()),   // actual broadcast send time (was stale cell B9)
    CurrentMonth: reportSheet.getRange('B3').getValue(),
    NumPaid: reportSheet.getRange('B4').getValue(),
    NumAdvancePaid: reportSheet.getRange('B5').getValue(),
    NumPending: reportSheet.getRange('B6').getValue(),
    CurrentMonthAmount: formatNumber(reportSheet.getRange('B7').getValue()),
    HouseNoPending: reportSheet.getRange('B8').getValue()
  };

  Logger.log(JSON.stringify(CommonfeeReport, null, 2));

  const flexJson = flexMessageSheet.getRange(cellRef).getValue();
  const flexMessage = replaceVariables(JSON.parse(flexJson), CommonfeeReport);

  Logger.log("📦 Final Flex Message:\n" + JSON.stringify(flexMessage, null, 2));

  const lineHeader = {
    "Content-Type": "application/json",
    "Authorization": "Bearer " + accessToken
  };

  const payload = {
    to: targetId,  // ✅ can be groupId or userId
    messages: [
      {
        type: "flex",
        altText: "สรุปรายงานชำระค่าส่วนกลาง",
        contents: flexMessage
      }
    ]
  };

  const options = {
    method: "post",
    headers: lineHeader,
    payload: JSON.stringify(payload)
  };

  const response = UrlFetchApp.fetch("https://api.line.me/v2/bot/message/push", options);
  Logger.log(response.getContentText());

  logMessageSent(CommonfeeReport);  // <-- Pass the actual object

}


function DateConvert(date) {
  if (!(date instanceof Date)) {
    date = new Date(date);
  }
  if (isNaN(date)) {
    return "-";
  }

  const yyyy = date.getFullYear().toString();
  const mm = (date.getMonth() + 1).toString().padStart(2, '0');
  const dd = date.getDate().toString().padStart(2, '0');

  return `${dd}-${mm}-${yyyy}`;
}


function replaceVariables(obj, variables) {
  const json = JSON.stringify(obj);
  const replaced = json.replace(/{{(.*?)}}/g, (match, p1) => {
    const value = variables[p1.trim()];
    return (value !== undefined && value !== null && value !== "") ? value.toString() : "-";
  });
  return JSON.parse(replaced);
}


function replaceVariablesInString(str, variables) {
  for (var key in variables) {
    var placeholder = "{{" + key + "}}";
    if (str.includes(placeholder)) {
      str = str.replace(placeholder, variables[key]);
    }
  }
  return str;
}

function logMessageSent(data) {
  const logSheetName = "MessageLog";
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let sheet = ss.getSheetByName(logSheetName);

  if (!sheet) {
    sheet = ss.insertSheet(logSheetName);
    sheet.appendRow([
      "Timestamp",
      "CurrentMonth",
      "NumPaid",
      "NumAdvancePaid",
      "NumPending",
      "CurrentMonthAmount",
      "HouseNoPending"
    ]);
  }

  const now = new Date();
  const row = [
    now.toLocaleString("th-TH"),
    data?.CurrentMonth || "-",
    data?.NumPaid || "-",
    data?.NumAdvancePaid || "-",
    data?.NumPending || "-",
    data?.CurrentMonthAmount || "-",
    data?.HouseNoPending || "-"
  ];

  sheet.appendRow(row);
}


function summarizePaymentByHouse(houseNo) {
    // 🔹 1. Sheet Setup & Data read
    // consolidate payment sheet included app paid transactions
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("ConsolidatePayments");
    // pending sheet summarize of unpaid member in year 2025
  const pendingSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Pending 2025");
  //const trackerSheet = ss.getSheetByName("PendingTracker"); // ✅ Added: sheet for historical pending

    // Loads all rows (except headers) from the ConsolidatePayments sheet into a 2D array data.
  const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, sheet.getLastColumn()).getValues();

    // 🔹 2. Ensures the input is a valid house number between 1–70.
  const houseInt = parseInt(houseNo);
  if (isNaN(houseInt) || houseInt < 1 || houseInt > 70) {
    return `บ้านเลขที่ ${houseNo} ไม่ถูกต้อง (ระบุเลขระหว่าง 1–70)`;
  }

    // 🔹 3. Filter Payment Rows for That HouseNo ( from user query )
     // Filters data to only rows with matching house number (Column A).
  const filtered = data.filter(row => row[0].toString().trim() === houseNo.toString().trim());
  const parsed = [];
    // Gets masked name from Column Q if available. ดึงชื่อสมาชิก (ที่ถูกแมสก์ไว้) จากคอลัมน์ Q (index 16)
    // ของ แถวแรกที่ตรงกับเลขบ้าน (filtered[0]) ซึ่งเป็น ค่าเดียวกัน สำหรับทุกรายการของบ้านเลขที่เดียวกัน ไม่ได้วนลูป
  let nameMask = filtered[0]?.[16] || "";

   // 🔹 4. Loop Through Rows: Extract and Clean Each Entry
  for (let i = 0; i < filtered.length; i++) {
    const row = filtered[i];
    const rawReceiptNo = row[5];    // Column F: ใบเสร็จ
    const type = row[9];            // Column J: ประเภทรายรับ
    const rawAmount = row[8];       // Column I: จำนวนเงิน
    const rawPayDate = row[14];     // Column O: ชำระเดือน
    const rawPaidDate = row[7];     // Column H: วันที่ชำระ
    const advanceType = row[11];    // Column L: ล่วงหน้า?

     // Skips any non-relevant rows (not “ค่าส่วนกลาง” or “ค่าจอดรถ” or missing date).
    if (!["ค่าส่วนกลาง", "ค่าจอดรถ"].includes(type) || !rawPayDate) continue;

     // Cleans up and parses:
    const payDate = new Date(rawPayDate);
    const paidDate = new Date(rawPaidDate);
    const cleanReceiptNo = parseInt(rawReceiptNo.toString().replace(/[^\d.]/g, ""));
    const cleanedAmount = parseFloat(rawAmount.toString().replace(/[^\d.]/g, ""));

    if (isNaN(payDate)) continue;

      // Pushes a structured object for valid payments: อยู่ใน for loop ที่วน filtered เพื่อเก็บเฉพาะรายการชำระที่ถูกต้อง
    parsed.push({
      payDate,
      paidDate,
      cleanReceiptNo,
      amount: isNaN(cleanedAmount) ? 0 : cleanedAmount,
      isAdvance: advanceType?.toString().trim() === "ล่วงหน้า",
      payMonthText: payDate.toLocaleString("th-TH", { month: "short" }),
      payMonthYearText: payDate.toLocaleString("th-TH", { month: "long", year: "2-digit" }),
      payDateText: paidDate.toLocaleString("th-TH", { day: "numeric", month: "short", year: "2-digit" })
    });
  }

   // 🔹 5. Get Most Recent Valid Payment
  const latest = parsed.sort((a, b) => b.paidDate - a.paidDate).find(p => !isNaN(p.paidDate));

   // 🔹 6. Filter Payments This Year
  const thisYear = new Date().getFullYear();
  const paidThisYear = parsed.filter(entry => entry.payDate.getFullYear() === thisYear);

   // 🔹 7. Summarize Paid Months and Amounts
     // Extracts unique paid months to avoid double-counting.
  const uniqueMonths = [...new Set(paidThisYear.map(e => e.payDate.getMonth()))].sort((a, b) => a - b);
     // total amount paid in the year.
  const total = paidThisYear.reduce((sum, entry) => sum + entry.amount, 0);
     // monthCount based on unique months.
  const monthCount = uniqueMonths.length;

   // 🔹 8. Format Thai Month Names
  const getThaiMonth = (dateObj) => dateObj.toLocaleString("th-TH", { month: "short" });
  const firstMonth = getThaiMonth(new Date(thisYear, uniqueMonths[0]));
  const lastMonth = getThaiMonth(new Date(thisYear, uniqueMonths[uniqueMonths.length - 1]));

  const thaiYearNow = new Date().getFullYear() + 543;   // เช่น 2569
  const cutoffThaiYear = thaiYearNow;                  // แสดง “ก่อนปี 2569”

   // 🔹 9. Generate Text Summary
  let result = `บ้านเลขที่ ${houseNo}:`;
  if (nameMask) result += ` คุณ ${nameMask}`;
  if (latest) {
    result += `\nชำระล่าสุดเมื่อ ${latest.payDateText} ใบเสร็จ ${latest.cleanReceiptNo} สำหรับเดือน ${latest.payMonthYearText}${latest.isAdvance ? " (ล่วงหน้า)" : ""}`;
  }
  if (monthCount > 0) {
    result += `\nรวมชำระปีนี้ ${monthCount} เดือน (${firstMonth} - ${lastMonth}) เป็นจำนวน ${total.toLocaleString("th-TH", { minimumFractionDigits: 0 })} บาท`;
  }
  
  

  // Step 2: Check pending from Pending 2025 sheet
  const currentMonthDate = new Date(pendingSheet.getRange("A2").getValue());
  const monthHeaders = pendingSheet.getRange("B5:O5").getValues()[0];
  const pendingData = pendingSheet.getRange("B8:O8").getValues()[0];

  let pendingMonths = [];

  for (let i = 0; i < pendingData.length; i++) {
    const cellRaw = pendingData[i].toString();
    const houseList = cellRaw
    .split(",")
    .map(h => h.replace(/[^\d]/g, '').trim())
    .filter(h => h !== "");
    
    if (houseList.includes(houseNo.toString())) {
      pendingMonths.push(monthHeaders[i]);
    }
  }

  if (pendingMonths.length > 0) {
    const fromMonth = pendingMonths[0];
    const toMonth = pendingMonths[pendingMonths.length - 1];
    const pendingAmount = pendingMonths.length * 1300;

    result += `\nมียอดค้างชำระ ${pendingMonths.length} เดือน (${fromMonth}${fromMonth !== toMonth ? " - " + toMonth : ""}) เป็นจำนวน ${pendingAmount.toLocaleString("th-TH", { minimumFractionDigits: 0 })} บาท`;
   
  }

  // ✅ New Step 3: Add historical pending lookup from PendingTracker
const trackerSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("PendingTracker");
let trackerNote = "";

if (trackerSheet) {
  const trackerData = trackerSheet.getRange("B6:K14").getValues(); // Row = houseNo, Col = year 2565–2567
  
  // Filter rows for this house number
  const matchingRows = trackerData.filter(row => row[0] && row[0].toString().trim() === houseNo.toString());

  // Group by year (column J → index 8), sum amounts (column K → index 9)
  const grouped = {};

  for (const row of matchingRows) {
    const year = row[7];      // Column J: ปี
    const amountStr = row[9]; // Column K: จำนวนเงิน

    const cleanAmount = parseFloat(amountStr.toString().replace(/[^\d.]/g, ""));
    if (!isNaN(cleanAmount)) {
      if (!grouped[year]) grouped[year] = 0;
      grouped[year] += cleanAmount;
    }
  }

  // === Format and append to trackerNote if we have valid data ===
  const yearList = Object.keys(grouped).sort();
  for (const y of yearList) {
    const baht = grouped[y].toLocaleString("th-TH");
    trackerNote += `\n• ปี ${y} รวมเป็น ${baht} บาท`;
  }

  if (trackerNote) {
    result += `\n\nยอดค้างชำระก่อนปี ${cutoffThaiYear}:${trackerNote}`;
  }
}



  return result;
}



function getMonthNameRange(dateString) {
  const date = new Date(dateString);
  const options = { month: 'long' };
  const month = date.toLocaleString('th-TH', options); // Thai full month
  const year = date.getFullYear().toString().slice(-2); // Last 2 digits
  return `${month} ${year}`;
}

function doPost(e) {
  try {
    // 🔹 1. Validate incoming request
    if (!e || !e.postData || !e.postData.contents) {
      throw new Error("Missing postData");
    }

    // 🔹 2. Parse LINE webhook payload
    const json = JSON.parse(e.postData.contents);
    const event = json.events && json.events[0];

    if (!event || event.type !== "message" || event.message.type !== "text") {
      Logger.log("📛 Ignored non-text message or missing event");
      return ContentService.createTextOutput("OK");
    }

    // 🔹 3. Log message source for debug (group/user/room)
    Logger.log("📥 Event: " + JSON.stringify(event));
    Logger.log("🔸 Source Type: " + event?.source?.type);

    // 🔹 4. Ignore message from group/room – only allow 1-on-1 user chat
    if (event.source.type !== "user") {
      Logger.log("📛 Ignored non-user message from: " + JSON.stringify(event.source));
      return ContentService.createTextOutput("OK");
    }

    // 🔹 5. Handle user message
    const userText = event.message.text.trim();
    const replyToken = event.replyToken;
    const userId = event.source.userId;
    let replyText = "";

    // 🏠 5a. House number input (1–70)
    if (/^\d+$/.test(userText)) {
      const houseNo = parseInt(userText, 10);
      if (houseNo >= 1 && houseNo <= 70) {
        try {
          replyText = summarizePaymentByHouse(houseNo);
        } catch (err) {
          replyText = `❌ เกิดข้อผิดพลาดขณะดึงข้อมูลบ้านเลขที่ ${houseNo}`;
          Logger.log("❌ summarizePaymentByHouse error: " + err.message);
        }
      } else {
        replyText = `🏠 บ้านเลขที่ไม่ถูกต้อง (กรุณาระบุเลขระหว่าง 1–70)`;
      }

    // 📊 5b. Request report
    } else if (userText === "รายงาน") {
      try {
        sendFlexReportUsingTemplate("C2", userId);  // Send to user only
        replyText = "📊 ส่งรายงานให้คุณเรียบร้อยแล้วครับ";
      } catch (err) {
        replyText = "❌ ไม่สามารถสร้างรายงานได้";
        Logger.log("❌ sendFlexReportUsingTemplate error: " + err.message);
      }

    // ℹ️ 5c. Help message
    } else {
      replyText = `ℹ️ กรุณาพิมพ์เลขบ้าน (1–70) หรือพิมพ์ "รายงาน" เพื่อขอรายงานค่าส่วนกลาง`;
    }

    // 🔹 6. Send reply to user
    replyMessage(replyToken, replyText);

  } catch (error) {
    Logger.log("❌ Error in doPost: " + error.message);
  }

  return ContentService.createTextOutput("OK");
}

// helper function 
function replyMessage(replyToken, replyText) {
  const payload = {
    replyToken: replyToken,
    messages: [
      {
        type: "text",
        text: replyText
      }
    ]
  };

  UrlFetchApp.fetch("https://api.line.me/v2/bot/message/reply", {
    method: "post",
    contentType: "application/json",
    headers: {
      Authorization: "Bearer " + accessToken
    },
    payload: JSON.stringify(payload)
  });
}

function doGet(e) {
  return HtmlService.createHtmlOutputFromFile('index')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

function testPendingLog() {
  const result = summarizePaymentByHouse(65); // Replace with test HouseNo
  Logger.log(result);
}

